version: "3"
services:
  db:
    image: postgres:12.2-alpine
    container_name: postgres
    ports:
    - 5432:5432
    volumes:
    - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 45685255
      POSTGRES_DB: PulseDB
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/pgdata
    restart: always

